name: Deploy Latest Test Version to test.loopedinlearning.io

on:
  push:
    branches:
      - main
    paths:
      - "apps/app/**"

env:
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_TEST_APP_PROJECT_ID }}

jobs:
  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code at tag
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.ref }}

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.2.5

      - name: Install Vercel CLI
        run: npm install -g vercel@canary

      # - name: Install dependencies
      #   run: bun install

      - name: Pull Vercel config
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build frontend
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy to Vercel Preview
        id: deploy
        run: vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }}
