name: Update the Test Environmentâ€™s Backend with the Latest Code

on:
  push:
    paths:
      - "packages/backend/**"
    branches:
      - main

jobs:
  deploy-convex-dev:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: 1.2.5

      - name: Install Root Dependencies
        run: bun install

      - name: Install Backend Dependencies
        run: bun install
        working-directory: packages/backend

      - name: Deploy to Convex (Dev)
        run: bunx convex deploy
        working-directory: packages/backend
        env:
          CONVEX_DEPLOY_KEY: ${{ secrets.CONVEX_DEPLOY_KEY_TEST }}
